### ISSUE TITLE
Support Grails 3

### ISSUE THREAD

**Issue by zyro23** [longwa/build-test-data#49] opened 2015-03-03 19:27 UTC
given Grails-3.0.0 just reached M2 and a final is planned to be released soon, it would be nice to see this plugin work with Grails 3 :)

thanks, zyro

**Comment by rafaelfelini** [comment] 2015-03-20 17:15
+1

**Comment by rafaelfelini** [comment] 2015-03-24 14:50
@tednaleid I converted the plugin to grails 3 structure and apparently it is working fine. What do you think that is the best way to publish the plugin? I could do a pull request but the structure of grails 2 and 3 are different, so I think the best way is to create a new repo and publish to bintray.

**Comment by zyro23** [comment] 2015-04-05 08:10
any news here? grails 3.0.1 has been released in the meantime. thanks, zyro

**Comment by longwa** [comment] 2015-04-06 01:25
@zyro23 I haven't had a chance to play around with 3.0.x. We are in the final stretch of our initial Grails 2.4.x deployment and will likely not be going to 3.0 until after our first release. I would love to get BTD officially working in 3.0 but I just haven't had any time to spend on it. Sounds like based on @rafaelfelini report, may not be much to do here.

**Comment by tednaleid** [comment] 2015-04-06 02:02
If all of the tests on @rafaelfelini's update pass, I'd consider releasing that.  

I'm pretty iffy overall about just upgrading build-test-data to grails 3 and releasing it.  BTD was originally created ~6 years ago with grails 1.0.X.  It's core model is very old-school grails (messing with the meta class of the domain classes and adding what appear to be static methods).

It hasn't aged well, it doesn't perform well and doesn't fit with the way that grails 3 does things now.  Bringing the current codebase into grails 3 feels like it would be a maintenance issue ongoing, especially with the way the unit and integration tests work now.  The changes for making unit tests works with annotations are not clean.

I've got a few ideas about changes I'd like to make to how build-test-data works to update it into working the way grails 3 works.  Changes that would also support working with standalone GORM.

I've taken a couple of stabs at it, but have had some real troubles with getting grails 3 to work well in a development environment (Intellij) and with the new gradle build system so I don't see this coming in the next few weeks.

At a high level, my current ideas are implementing BTD as a jar file that would have a `Build` `trait` that you could implement in your tests (unit or integration).  We would drop the `@Build` annotation, and we would no longer decorate the metaclass of all of the domain classes with a `build` method.

Instead, if your test implements the `Build` `trait` it would get a `build` method with a few signatures:

- `build(Class clazz)` - takes a domain class as a parameter and returns a newly built instance
    - ex: `build(Book)` - returns a new `Book` instance that has the required `Author`
- `build(Class clazz, Map<String, Object> properties)`
    - ex: `build(Book, [title: 'Infinite Jest'])` - returns a new `Book` with the specified `title` and the required `Author` attached to it
- `build(Object domainClassInstance)` - takes a partially filled in, but unsaved domain class and fills in the other required pieces and then saves it
    - ex: `build(new Book(title: 'Grapes of Wrath'))` - returns updated instance that has the required `Author` built and attached to it

Implementing it as a `trait` would allow you to mix it in to any test that needed it.  In unit tests, you'd just `@Mock` out the domain classes you wanted to use just like any normal unit test would have to.  In integration tests it'd just work.

You could also subclass the `Build` `trait` with your own behavior and that would give you the ability to add in things that we now put in the `TestDataConfig.groovy` file, or have behavior that's overridden in the test itself.  

Using a `trait` and a `jar` file would also get rid of a complaint that I've gotten a lot over the years about how BTD isn't test-only by default and it still decorates your domain classes in production (unless you explicitly make it a test plugin, but most don't do that).

I think these changes would be a lot more in line with how grails 3 works, and would get away from all of the fragility and messiness of mucking with the `metaClass`.  The grails framework moved away from this for a reason.

**Comment by longwa** [comment] 2015-04-06 02:39
@tednaleid Another option would be to keep the @Build annotation and use an AST Transformation to add a 'Buildable' trait at compile time. I believe that is essentially what Grails 3 is doing with many of the artifacts like domains, services, etc. You could still implement the Trait yourself (and subclass if desired) but it would be more backwards compatible with existing usages. 

One big (sort of) downside is that it would require you to use @Build for both unit AND integration tests. Personally, I like having the @Build line at the top of a test b/c it gives me a simple outline of what domains this particular test is touching. If I see a ton of things in that line, it's a red flag that maybe things need to be split up.

Anyway, just thinking out loud really.

**Comment by tednaleid** [comment] 2015-04-06 03:03
Thanks for the ideas @longwa, that's what I'm looking for at this stage.  

The things that I like about having a trait that you implement in your test (or wherever) are:
- it's something that the end user could easily override and create their own trait to override behavior.  Maybe one trait that has one set of defaults specific to a difficult scenario that you wouldn't want to use in other parts of the code.  
- IDEs are aware of traits and can help you with autocompletion.  

With things like the `@Build` annotation, they don't offer any real extensibility and an IDE doesn't have a clue what kind of methods that you'll be adding to a class.

If we went the `@Build` way, I wouldn't actually mind the requirement to have it on integration tests as well, as that's often bitten people who are coding both kinds of tests.  Currently, putting a `@Build` annotation on an integration test causes all kinds of Bad Problems and it's an easy mistake to make.  Especially if you're converting a test from one type to another.

Are there other advantages to having an annotation add a `Buildable` trait at compile time (rather than just adding the trait directly) that I'm missing?

**Comment by zyro23** [comment] 2015-04-06 06:53
@tednaleid sounds good. in that case, better take the time it needs to get a updated grails3 release ready instead of just rushing out a "compatibility" version. thanks!

**Comment by longwa** [comment] 2015-04-06 20:01
@tednaleid The trait is certainly better for IDE autocomplete and being able to extend and override. I was just proposing something that might help with upgrading existing tests.

Regardless of which approach, you still need to keep @Build as @Mock doesn't resolve dependent classes in the same way. It's very nice to have @Build essentially mock the other required classes in the graph, otherwise you end up with a lot more burden on the test author for building the graph.

Also, in my latest changes for 2.4, the @Build handling has already been moved into the current grails world by removing the AST transformation and using Lari's test plugin infrastructure. The `BuildTestDataTestPlugin implements TestPlugin` which provides a supported hook for doing what we need to do in what seems like a standardized way. From the sound of it, that way has stayed the same in 3.0 so I'm hopeful that we are on the right path there.

-Aaron

**Comment by kyleboon** [comment] 2015-04-07 18:57
I'd really like the ability to either a) For BTD to either not add Author to Book or b) specify a depth for how deep BTW should go into the domain graph. 

Creating large dependency graphs can be pretty expensive and not necessary in most cases.

**Comment by longwa** [comment] 2015-04-07 19:23
@kyleboon BTD only builds dependent objects in order to satisfy constraints. If a Book belongs to an Author and Author is required, you can't really build (and save) a Book without building an Author.

I guess you could do a buildWithoutSave() but the typically use-case is that you want to create a known "database" state before running your test code. I agree it's expensive, but I'm not sure I see the alternative.

If we added a buildThisOnly() method for Book in my example, calling save() would fail.

**Comment by kyleboon** [comment] 2015-04-07 19:33
I would do save(validate: false) for Author.

**Comment by tednaleid** [comment] 2015-04-07 20:43
@kyleboon that works for unit tests that aren't backed by a real DB where you don't want a valid `Author` and your code doesn't care about it really passing validation, just that it's an `Author` with maybe the `firstName` you're looking for.

Is there a reason that you'd want to use BTD for that object rather than just doing the `new Author(name: 'Ted').save(validate: false)` instead?  Does BTD bring something by being able to populate some of the values on `Author`, but not the related objects?  What kinds of tests would that be useful for?

**Comment by Luxor** [comment] 2015-08-18 10:05
+1

**Comment by dmahapatro** [comment] 2015-09-29 02:16
@tednaleid Will it be a good idea to release @rafaelfelini 's PR (BTD for Grails 3) until that is replaced with "Spackle"? Secondly, when is the plan for Spackle's milestone? :)

**Comment by Luxor** [comment] 2015-10-05 10:47
any updates?

**Comment by longwa** [comment] 2015-10-15 17:09
I started a discussion with @tednaleid about the future of BTD. I'm in a position soon to be able to spend some time on our application and making sure that @rafaelfelini PR works well. Hopefully we can figure something out soon.

**Comment by tednaleid** [comment] 2015-10-15 17:20
I understand the void that's caused by not having a BTD equivalent for grails 3.0 for those that've been able to make the switch.  Progress on Spackle (my replacement project) hasn't been as quick as I'd hoped it'd be (and it's still likely a long way off).

I still believe that BTD is the wrong model for the grails 3.0 world and I'm not personally willing to develop/support that migration.  

@longwa if you'd like to make a fork of the project and take full ownership of BTD for grails 3.0 and the work necessary to support and release it, I'd be willing to deprecate this repo and point it at your version.

I'd rather not have dev continue under my user account on github for something I'm not willing to do further dev on.

**Comment by longwa** [comment] 2015-10-15 18:32
@tednaleid I think BTD will be essential for us in the near term so I'm happy to take ownership and keep the lights on for a while longer.

The cleanest solution would be to just Transfer Ownership of this repository. That would retain the Wiki, Issues, etc.

We would also need to ensure that I can publish the new plugin to the Grails bintray (not sure the process for that one).

I'd love to discuss your ideas for the new model and would be willing to provide feedback once you get things rolling.

**Comment by tednaleid** [comment] 2015-10-15 18:35
@longwa transfer request sent

**Comment by longwa** [comment] 2015-10-16 13:43
@rafaelfelini Can you submit a pull request for your changes? I don't see any open pull requests at the moment.

**Comment by rafaelfelini** [comment] 2015-10-20 02:46
Hi @longwa I made the pull request https://github.com/longwa/build-test-data/pull/54

**Comment by longwa** [comment] 2015-10-22 14:38
@rafaelfelini Thanks! I've merged your changes and now I'm porting the other test applications. Should have something to release in the next day or two.

**Comment by longwa** [comment] 2015-10-26 17:04
Request submitted to include 3.0.0 in the grails/plugins repo. Should be available shortly.

**Comment by dmahapatro** [comment] 2015-10-26 17:28
@longwa, @rafaelfelini & @tednaleid  +1. Thanks for making it a priority. I believe with the release of Grails 3 version of btd, there is not stopping for migrating enterprise level apps to Grails 3. :)

**Comment by longwa** [comment] 2015-10-26 17:39
@dmahapatro Well, Grails 3 has been out for 6 months so I feel bad if it's been holding people back. The problem that I'm sure many have is that our own company application is on 2.4.4 so it's hard to support plugins when I don't have a use case for my own work. We are moving to 3.0 soon and BTD is a vital part of our testing as well.

**Comment by dmahapatro** [comment] 2015-10-26 17:50
@longwa Same here, all our apps are on 2.4.4 and we are in a position to move them to 3.0.9 in couple of weeks/days. BTD will be the only plugin dependency that would be stopping us to move if we move today.

**Comment by longwa** [comment] 2015-10-27 13:47
The plugin is now available in the grails bintray.

**Closed by longwa** 2015-10-27 13:47 UTC

**Comment by jrgleason** [comment] 2016-05-12 17:38
Is there a new syntax or something? http://stackoverflow.com/questions/37193374/grails-3-upgrade-test-issues
